services:
    php-cli:
        container_name: ${APP_NAME}-php-cli
        build:
            context: docker
            dockerfile: php-cli/Dockerfile
        restart: always
        volumes:
            - ./project:/project
        networks:
            - micro-service

    maria-db:
        restart: always
        image: mariadb:11.1.3
        container_name: ${APP_NAME}-db
        volumes:
            - ./volumes/database/mysql://var/lib/mysql
        ports:
            - "3355:3306"
        command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
        environment:
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        networks:
            - micro-service

networks:
    micro-service:
        external: true
